import type { SiteContent } from './types';

export const defaultContent: SiteContent = {
  hero: {
    eyebrow: { pt: 'CADERNO ABERTO · 2026', en: 'OPEN NOTEBOOK · 2026' },
    title: {
      pt: 'Crio coisas que não cabem numa só caixa.',
      en: 'I make things that do not fit in one box.',
    },
    lead: {
      pt: 'Este é o lugar onde junto ideias sérias, testes aleatórios, projetos pessoais, fases da vida e coisas que fiz só porque parecia divertido.',
      en: 'This is where I gather serious ideas, random experiments, personal projects, chapters of life and things I made simply because they sounded fun.',
    },
  },
  metrics: [
    { id: 'fronts', value: '07', label: { pt: 'territórios que já explorei', en: 'territories explored' } },
    { id: 'views', value: '26,6 mi', label: { pt: 'vezes que algo encontrou alguém', en: 'times something found someone' } },
    { id: 'systems', value: '02', label: { pt: 'jeitos de organizar o caos', en: 'ways of organizing chaos' } },
    { id: 'languages', value: 'PT/EN', label: { pt: 'idiomas da mesma curiosidade', en: 'languages for the same curiosity' } },
  ],
  story: [
    {
      id: 'curiosity', index: '01',
      eyebrow: { pt: 'UMA FAÍSCA', en: 'A SPARK' },
      title: { pt: 'Curiosidade', en: 'Curiosity' },
      body: { pt: 'Alguma coisa me intriga e eu preciso descobrir o que acontece se eu seguir a ideia.', en: 'Something intrigues me and I need to find out what happens if I follow the idea.' },
      stat: 'WHY?', accent: '#ff6b4a',
    },
    {
      id: 'play', index: '02',
      eyebrow: { pt: 'SEM PRECISAR JUSTIFICAR', en: 'NO NEED TO EXPLAIN' },
      title: { pt: 'Brincadeira', en: 'Play' },
      body: { pt: 'Misturo ferramentas, referências e formatos sem exigir que o resultado seja útil.', en: 'I mix tools, references and formats without demanding that the result be useful.' },
      stat: 'PLAY', accent: '#76d7c4',
    },
    {
      id: 'deep-dive', index: '03',
      eyebrow: { pt: 'QUANDO A IDEIA FICA', en: 'WHEN THE IDEA STICKS' },
      title: { pt: 'Mergulho', en: 'Deep dive' },
      body: { pt: 'Volto, erro, refaço, pesquiso demais e vejo até onde aquela coisa quer ir.', en: 'I return, fail, remake, research too much and see how far that thing wants to go.' },
      stat: 'AGAIN', accent: '#b7a6ff',
    },
    {
      id: 'affection', index: '04',
      eyebrow: { pt: 'PORQUE IMPORTA PARA MIM', en: 'BECAUSE IT MATTERS TO ME' },
      title: { pt: 'Afeto', en: 'Affection' },
      body: { pt: 'Algumas coisas existem por uma pessoa, uma fase, uma piada interna ou uma lembrança.', en: 'Some things exist for a person, a chapter of my life, an inside joke or a memory.' },
      stat: '<3', accent: '#f6c760',
    },
    {
      id: 'trace', index: '05',
      eyebrow: { pt: 'PARA NÃO PASSAR EM BRANCO', en: 'SO IT DOES NOT DISAPPEAR' },
      title: { pt: 'Rastro', en: 'A trace' },
      body: { pt: 'Se ficou pronto, ótimo. Se virou aprendizado, também. Os dois merecem um lugar aqui.', en: 'Whether it became something finished or simply taught me something, it deserves a place here.' },
      stat: 'KEEP', accent: '#ff7fac',
    },
  ],
  projects: [
    {
      id: 'canal-decisao', slug: 'canal-decisao', kind: 'highlight',
      category: { pt: 'Conteúdo & mídia', en: 'Content & media' },
      title: { pt: 'Canal Decisão', en: 'Canal Decisão' },
      summary: { pt: 'Futebol em vídeo — da pauta ao corte final, com identidade própria e comunidade ativa.', en: 'Football on video — from story to final cut, with its own identity and an active community.' },
      image: '/media/decisao/banner-canal.png',
      alt: { pt: 'Banner do Canal Decisão', en: 'Canal Decisão banner' },
      accent: '#ff6b4a', year: '2026', tags: ['YouTube', 'CapCut', 'Brand'],
      href: 'https://www.youtube.com/@ocanaldecisao', featured: true, visible: true, position: 0,
      metrics: [
        { id: 'subs', value: '25,1 mil', label: { pt: 'inscritos', en: 'subscribers' } },
        { id: 'videos', value: '320', label: { pt: 'vídeos', en: 'videos' } },
        { id: 'views', value: '26,6 mi', label: { pt: 'visualizações', en: 'views' } },
      ],
    },
    {
      id: 'mirtillo', slug: 'mirtillo', kind: 'highlight',
      category: { pt: 'Design & marca', en: 'Design & brand' },
      title: { pt: 'Mirtillo', en: 'Mirtillo' },
      summary: { pt: 'Posicionamento, identidade e uma linguagem visual feita para mostrar o próximo passo.', en: 'Positioning, identity and a visual language made to reveal the next step.' },
      image: '/media/mirtillo/mirtillo-app.png',
      alt: { pt: 'Interface da marca Mirtillo', en: 'Mirtillo brand interface' },
      accent: '#f6c760', year: '2026', tags: ['Identity', 'Strategy', 'UI'],
      featured: true, visible: true, position: 1,
    },
    {
      id: 'notion', slug: 'sistema-notion', kind: 'project',
      category: { pt: 'Estudos & sistemas', en: 'Learning systems' },
      title: { pt: 'Sistema de estudos', en: 'Learning system' },
      summary: { pt: 'Períodos, matérias, tarefas e anotações conectados em um espaço que acompanha o aprendizado.', en: 'Terms, classes, tasks and notes connected in a space that follows the learning process.' },
      image: '/media/notion/notion-01-cover-planner.png',
      alt: { pt: 'Capa do planner no Notion', en: 'Notion planner cover' },
      accent: '#68c9ff', year: '2026', tags: ['Notion', 'Obsidian', 'AI'],
      featured: false, visible: true, position: 2,
    },
    {
      id: 'futebol', slug: 'futebol', kind: 'project',
      category: { pt: 'Esporte', en: 'Sports' },
      title: { pt: 'Antes de programar, eu jogava', en: 'Before coding, I played' },
      summary: { pt: 'Registros de uma fase competitiva que ainda influencia meu jeito de trabalhar em equipe.', en: 'Records from a competitive phase that still shapes how I work with a team.' },
      image: '/media/esporte/partida.jpg',
      alt: { pt: 'Gustavo em uma partida de futebol', en: 'Gustavo during a football match' },
      accent: '#76d796', year: 'Arquivo', tags: ['Football', 'Team'],
      featured: false, visible: true, position: 3,
    },
    {
      id: 'voluntariado', slug: 'dia-do-voluntario', kind: 'project',
      category: { pt: 'Impacto social', en: 'Social impact' },
      title: { pt: 'Dia do Voluntário', en: 'Volunteer Day' },
      summary: { pt: 'Jardinagem, reforma e atividades com as crianças no Colégio Estadual Deputado Olívio Belich.', en: 'Gardening, renovation and activities with children at Colégio Estadual Deputado Olívio Belich.' },
      image: '/media/voluntariado/01-grupo.jpg',
      alt: { pt: 'Grupo do Dia do Voluntário', en: 'Volunteer Day group' },
      accent: '#76d7c4', year: '2025', tags: ['Community', 'Vivo'],
      featured: false, visible: true, position: 4,
    },
    {
      id: 'newscope', slug: 'newscope-pibic', kind: 'project',
      category: { pt: 'Pesquisa', en: 'Research' },
      title: { pt: 'NewsScope · PIBIC', en: 'NewsScope · PIBIC' },
      summary: { pt: 'Interface web para análise automatizada de notícias, desenvolvida em iniciação científica.', en: 'A web interface for automated news analysis, developed during undergraduate research.' },
      image: '/media/comprovacoes/feedback-professor.png',
      alt: { pt: 'Registro do professor sobre o projeto PIBIC', en: 'Professor note about the PIBIC project' },
      accent: '#b7a6ff', year: '2026', tags: ['React', 'Research', 'ENoW'],
      featured: false, visible: true, position: 5,
    },
    {
      id: 'site-presente', slug: 'site-presente', kind: 'project',
      category: { pt: 'Projeto pessoal', en: 'Personal project' },
      title: { pt: 'Um site de presente', en: 'A website as a gift' },
      summary: { pt: 'Uma experiência construída com carinho, sem cliente e sem prazo.', en: 'An experience built with care, with no client and no deadline.' },
      image: '/media/pessoais/site-presente.png',
      alt: { pt: 'Capa do site de presente', en: 'Gift website cover' },
      accent: '#ff7fac', year: '2025', tags: ['Web', 'Personal'],
      href: 'https://gusggk.github.io/WebSite_by_My_GirlFriend/index-intro.html',
      featured: false, visible: true, position: 6,
    },
    {
      id: 'abimaball', slug: 'abimaball', kind: 'project',
      category: { pt: 'Jogo entre amigos', en: 'A game among friends' },
      title: { pt: 'ABIMABALL', en: 'ABIMABALL' },
      summary: { pt: 'Um jogo em Java simples, cheio de piadas internas e divertido de construir.', en: 'A simple Java game, full of inside jokes and fun to build.' },
      image: '/media/pessoais/abimaball.png',
      alt: { pt: 'Captura do jogo ABIMABALL', en: 'ABIMABALL game screenshot' },
      accent: '#ff7fac', year: '2025', tags: ['Java', 'Game'],
      href: 'https://github.com/GusGgk/AbimaBall',
      featured: false, visible: true, position: 7,
    },
  ],
};
