import type { SiteContent } from './types';

export const defaultContent: SiteContent = {
  hero: {
    eyebrow: { pt: 'ARQUIVO VIVO · 2026', en: 'LIVING ARCHIVE · 2026' },
    title: {
      pt: 'Crio coisas que não cabem numa só caixa.',
      en: 'I make things that do not fit in one box.',
    },
    lead: {
      pt: 'Mídia, identidade, sistemas de estudo, esporte e projetos pessoais — experiências construídas com curiosidade e acabamento.',
      en: 'Media, identity, learning systems, sports and personal projects — experiences built with curiosity and craft.',
    },
  },
  metrics: [
    { id: 'fronts', value: '07', label: { pt: 'frentes criativas', en: 'creative fields' } },
    { id: 'views', value: '26,6 mi', label: { pt: 'visualizações', en: 'views' } },
    { id: 'systems', value: '02', label: { pt: 'sistemas de estudo', en: 'learning systems' } },
    { id: 'languages', value: 'PT/EN', label: { pt: 'experiência bilíngue', en: 'bilingual experience' } },
  ],
  story: [
    {
      id: 'idea', index: '01',
      eyebrow: { pt: 'PONTO DE PARTIDA', en: 'STARTING POINT' },
      title: { pt: 'Ideia', en: 'Idea' },
      body: { pt: 'Tudo começa com uma pergunta boa o bastante para merecer forma.', en: 'Everything starts with a question good enough to deserve a form.' },
      stat: 'WHY?', accent: '#ff6b4a',
    },
    {
      id: 'system', index: '02',
      eyebrow: { pt: 'CLAREZA', en: 'CLARITY' },
      title: { pt: 'Sistema', en: 'System' },
      body: { pt: 'Organizo o caos em regras, relações e decisões que podem evoluir.', en: 'I organize chaos into rules, relationships and decisions that can evolve.' },
      stat: '02×', accent: '#76d7c4',
    },
    {
      id: 'interface', index: '03',
      eyebrow: { pt: 'EXPRESSÃO', en: 'EXPRESSION' },
      title: { pt: 'Interface', en: 'Interface' },
      body: { pt: 'A identidade aparece na tipografia, no ritmo e na hierarquia — nunca só na decoração.', en: 'Identity emerges through type, rhythm and hierarchy — never decoration alone.' },
      stat: 'UI', accent: '#b7a6ff',
    },
    {
      id: 'motion', index: '04',
      eyebrow: { pt: 'RITMO', en: 'RHYTHM' },
      title: { pt: 'Movimento', en: 'Motion' },
      body: { pt: 'Animação orienta atenção, explica relações e dá personalidade à experiência.', en: 'Motion guides attention, explains relationships and gives the experience character.' },
      stat: '60', accent: '#f6c760',
    },
    {
      id: 'delivery', index: '05',
      eyebrow: { pt: 'MUNDO REAL', en: 'REAL WORLD' },
      title: { pt: 'Entrega', en: 'Delivery' },
      body: { pt: 'Publico, observo, aprendo e volto melhor para a próxima versão.', en: 'I ship, observe, learn and return better for the next version.' },
      stat: 'LIVE', accent: '#ff7fac',
    },
  ],
  projects: [
    {
      id: 'canal-decisao', slug: 'canal-decisao', kind: 'highlight',
      category: { pt: 'Conteúdo & mídia', en: 'Content & media' },
      title: { pt: 'Canal Decisão', en: 'Canal Decisão' },
      summary: { pt: 'Futebol em vídeo — da pauta ao corte final, com identidade própria e comunidade ativa.', en: 'Football on video — from story to final cut, with its own identity and an active community.' },
      image: '/media/decisao/banner-canal.png',
      alt: { pt: 'Banner do Canal Decisão', en: 'Canal Decisão banner' },
      accent: '#ff6b4a', year: '2026', tags: ['YouTube', 'CapCut', 'Brand'],
      href: 'https://www.youtube.com/@ocanaldecisao', featured: true, visible: true, position: 0,
      metrics: [
        { id: 'subs', value: '25,1 mil', label: { pt: 'inscritos', en: 'subscribers' } },
        { id: 'videos', value: '320', label: { pt: 'vídeos', en: 'videos' } },
        { id: 'views', value: '26,6 mi', label: { pt: 'visualizações', en: 'views' } },
      ],
    },
    {
      id: 'mirtillo', slug: 'mirtillo', kind: 'highlight',
      category: { pt: 'Design & marca', en: 'Design & brand' },
      title: { pt: 'Mirtillo', en: 'Mirtillo' },
      summary: { pt: 'Posicionamento, identidade e uma linguagem visual feita para mostrar o próximo passo.', en: 'Positioning, identity and a visual language made to reveal the next step.' },
      image: '/media/mirtillo/mirtillo-app.png',
      alt: { pt: 'Interface da marca Mirtillo', en: 'Mirtillo brand interface' },
      accent: '#f6c760', year: '2026', tags: ['Identity', 'Strategy', 'UI'],
      featured: true, visible: true, position: 1,
    },
    {
      id: 'notion', slug: 'sistema-notion', kind: 'project',
      category: { pt: 'Estudos & sistemas', en: 'Learning systems' },
      title: { pt: 'Sistema de estudos', en: 'Learning system' },
      summary: { pt: 'Períodos, matérias, tarefas e anotações conectados em um espaço que acompanha o aprendizado.', en: 'Terms, classes, tasks and notes connected in a space that follows the learning process.' },
      image: '/media/notion/notion-01-cover-planner.png',
      alt: { pt: 'Capa do planner no Notion', en: 'Notion planner cover' },
      accent: '#68c9ff', year: '2026', tags: ['Notion', 'Obsidian', 'AI'],
      featured: false, visible: true, position: 2,
    },
    {
      id: 'futebol', slug: 'futebol', kind: 'project',
      category: { pt: 'Esporte', en: 'Sports' },
      title: { pt: 'Antes de programar, eu jogava', en: 'Before coding, I played' },
      summary: { pt: 'Registros de uma fase competitiva que ainda influencia meu jeito de trabalhar em equipe.', en: 'Records from a competitive phase that still shapes how I work with a team.' },
      image: '/media/esporte/partida.jpg',
      alt: { pt: 'Gustavo em uma partida de futebol', en: 'Gustavo during a football match' },
      accent: '#76d796', year: 'Arquivo', tags: ['Football', 'Team'],
      featured: false, visible: true, position: 3,
    },
    {
      id: 'voluntariado', slug: 'dia-do-voluntario', kind: 'project',
      category: { pt: 'Impacto social', en: 'Social impact' },
      title: { pt: 'Dia do Voluntário', en: 'Volunteer Day' },
      summary: { pt: 'Jardinagem, reforma e atividades com as crianças no Colégio Estadual Deputado Olívio Belich.', en: 'Gardening, renovation and activities with children at Colégio Estadual Deputado Olívio Belich.' },
      image: '/media/voluntariado/01-grupo.jpg',
      alt: { pt: 'Grupo do Dia do Voluntário', en: 'Volunteer Day group' },
      accent: '#76d7c4', year: '2025', tags: ['Community', 'Vivo'],
      featured: false, visible: true, position: 4,
    },
    {
      id: 'newscope', slug: 'newscope-pibic', kind: 'project',
      category: { pt: 'Pesquisa', en: 'Research' },
      title: { pt: 'NewsScope · PIBIC', en: 'NewsScope · PIBIC' },
      summary: { pt: 'Interface web para análise automatizada de notícias, desenvolvida em iniciação científica.', en: 'A web interface for automated news analysis, developed during undergraduate research.' },
      image: '/media/comprovacoes/feedback-professor.png',
      alt: { pt: 'Registro do professor sobre o projeto PIBIC', en: 'Professor note about the PIBIC project' },
      accent: '#b7a6ff', year: '2026', tags: ['React', 'Research', 'ENoW'],
      featured: false, visible: true, position: 5,
    },
    {
      id: 'site-presente', slug: 'site-presente', kind: 'project',
      category: { pt: 'Projeto pessoal', en: 'Personal project' },
      title: { pt: 'Um site de presente', en: 'A website as a gift' },
      summary: { pt: 'Uma experiência construída com carinho, sem cliente e sem prazo.', en: 'An experience built with care, with no client and no deadline.' },
      image: '/media/pessoais/site-presente.png',
      alt: { pt: 'Capa do site de presente', en: 'Gift website cover' },
      accent: '#ff7fac', year: '2025', tags: ['Web', 'Personal'],
      href: 'https://gusggk.github.io/WebSite_by_My_GirlFriend/index-intro.html',
      featured: false, visible: true, position: 6,
    },
    {
      id: 'abimaball', slug: 'abimaball', kind: 'project',
      category: { pt: 'Jogo entre amigos', en: 'A game among friends' },
      title: { pt: 'ABIMABALL', en: 'ABIMABALL' },
      summary: { pt: 'Um jogo em Java simples, cheio de piadas internas e divertido de construir.', en: 'A simple Java game, full of inside jokes and fun to build.' },
      image: '/media/pessoais/abimaball.png',
      alt: { pt: 'Captura do jogo ABIMABALL', en: 'ABIMABALL game screenshot' },
      accent: '#ff7fac', year: '2025', tags: ['Java', 'Game'],
      href: 'https://github.com/GusGgk/AbimaBall',
      featured: false, visible: true, position: 7,
    },
  ],
};
